services:
  django:
    build:
      context: .
    container_name: bd
    ports:
      - "8001:8000"
    volumes:
      - ./bd/media:/app/bd/media
      - ./bd/database:/app/bd/database
    environment:
      - DEBUG=False
      - DJANGO_ENV=production
    env_file:
      - .env
    working_dir: /app/bd
    command: >
      sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - postgres
    networks:
      - bd_network

  postgres:
    image: postgres:15
    container_name: postgres_bd
    restart: always
    env_file:
      - .env
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bd_network

volumes:
  postgres_data:

networks:
  bd_network: