services:
  django:
    build:
      context: . # Emplacement du Dockerfile
    container_name: bd
    ports:
      - "8000:8000" # Expose le port 8000
    volumes:
      - ./bd/media:/app/bd/media # Monte le dossier local 'media' dans le conteneur
      - ./bd/database:/app/bd/database
    environment:
      - DEBUG=True
    command: >
      sh -c "python bd/manage.py migrate && python bd/manage.py runserver 0.0.0.0:8000"
