services:
  postgres:
    image: postgres:15
    container_name: postgres_bd
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comics
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
